sudo: required
language: node_js
node_js:
   - "11.10.1"
services: 
   - docker

before_install:
   - docker build -t vokidoki130/docker-react -f Dockerfile.dev .


script:
   - docker run vokidoki130/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-us-east-1-999994026265"
   bucket_path: "docker"
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
           secure: "$AWS_SECRET_KEY"
